trigger:
- none

pr:
- '*'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building the code..."
      displayName: "Build step"

- stage: WaitForApproval
  dependsOn: Build
  jobs:
  - deployment: ApprovalJob
    environment: 'PR-Approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Waiting for approval..."
            displayName: "Approval stage"

- stage: Deploy
  dependsOn: WaitForApproval
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying the code..."
      displayName: "Deploy step"

resources:
  environments:
  - name: 'PR-Approval'
    approvers:
      approvals:
        - identity: 'prauthor' # This will require approvals from the pull request reviewers.
        - identity: 'prauthor'
                  
